<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class M_Tbcomedy extends CI_Model
{

    public $table = 'tbcomedy';
    public $id = 'idComedy';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('idComedy', $q);
	$this->db->or_like('namaComedy', $q);
	$this->db->or_like('gambar', $q);
	$this->db->or_like('jenisComedy', $q);
	$this->db->or_like('tipeComedy', $q);
	$this->db->or_like('qtyComedy', $q);
	$this->db->or_like('harga', $q);
	$this->db->or_like('ketComedy', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('idComedy', $q);
	$this->db->or_like('namaComedy', $q);
	$this->db->or_like('gambar', $q);
	$this->db->or_like('jenisComedy', $q);
	$this->db->or_like('tipeComedy', $q);
	$this->db->or_like('qtyComedy', $q);
	$this->db->or_like('harga', $q);
	$this->db->or_like('ketComedy', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

// function _uploadImage()
// {
//     $config['upload_path']          = './assets/img/upload/';
//     $config['allowed_types']        = 'gif|jpg|png';
//     $config['file_name']            = $this->idComedy;
//     $config['overwrite']			= true;
//     $config['max_size']             = 1024; // 1MB
//     // $config['max_width']            = 1024;
//     // $config['max_height']           = 768;

//     $this->load->library('upload', $config);

//     if ($this->upload->do_upload('image')) {
//         return $this->upload->data("file_name");
//     }
    
//     return "default.jpg";
// }

}

/* End of file M_Tbcomedy.php */
/* Location: ./application/models/M_Tbcomedy.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-05-19 18:06:26 */
/* http://harviacode.com */